# Generated by Django 6.0.6 on 2026-06-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_text', models.CharField(max_length=500)),
                ('deadline', models.DateTimeField(verbose_name='deadline')),
                ('importance', models.BooleanField()),
            ],
        ),
    ]
