# Generated by Django 6.0.6 on 2026-06-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_remove_event_deadline_remove_event_importance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='importance',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
