# Generated by Django 6.0.6 on 2026-06-09 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0003_event_importance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="importance",
            new_name="important",
        ),
    ]
